load("//tools/build_defs/go:go_library.bzl", "go_library")
load("//tools/build_defs/go:go_test.bzl", "go_test")

go_library(
    name = "dataplexlookupentry",
    srcs = ["dataplexlookupentry.go"],
)

go_test(
    name = "dataplexlookupentry_test",
    srcs = ["dataplexlookupentry_test.go"],
)
