load("//tools/build_defs/go:go_library.bzl", "go_library")
load("//tools/build_defs/go:go_test.bzl", "go_test")

go_library(
    name = "dataplexsearchentries",
    srcs = ["dataplexsearchentries.go"],
)

go_test(
    name = "dataplexsearchentries_test",
    srcs = ["dataplexsearchentries_test.go"],
)
